[package]
name = "minnow-derive"
version = "0.1.0"
description = "A derive macro for the Minnow library."
edition = "2021"
license = "GPL-3.0"
repository = "https://github.com/danieleades/minnow"
keywords = ["compression", "encoding", "arithmetic-coding", "lossless"]
categories = ["compression", "encoding", "parsing"]
rust-version = "1.85"

[lib]
proc-macro = true

[dependencies]
darling = "0.20"
num-traits = "0.2"
proc-macro2 = "1.0.37"
quote = "1.0.17"
syn = "2"

[dev-dependencies]
proc-macro2 = "1.0.37"
test-case = "3.0.0"
