[package]
name = "minnow-derive"
version.workspace = true
description = "A derive macro for the Minnow library."
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
darling = "0.23"
num-traits = "0.2"
proc-macro2 = "1.0.37"
quote = "1.0.17"

[dev-dependencies]
proc-macro2 = "1.0.37"
test-case = "3.0.0"
